config/routes.rb
Kavaggregator::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :articles, only: [:index, :show]
  resources :comments, only: [:index, :create, :destroy, :new]
  resources :messages, only: [:index]
  match "feedbacks" => "feedbacks#send_feedback"

  namespace :admin do
    resources :published_articles, only: [:index] do
      collection do
        match :group
      end
      member do
        match :trend
        match :ungroup
      end
    end
    root :to => "articles#index"
    resources :news_sources do
      member do
        match :clear
      end
    end
    resources :keywords
    resources :categories
    resources :tags
    resources :trends
    resources :users
    resources :comments, only: [:index, :destroy, :show]
    resources :articles do
      member do
        match :train
        match :classify
      end
      collection do
        match :feed_me
      end
    end
    resources :messages
  end

  root to: "articles#index"

  # API
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :articles do
        member do
          post :share
          get :share
        end
      end
      resources :trends,       only: [:index]
      resources :categories,   only: [:index]
      resources :news_sources, only: [:index]
    end
  end

end

app/models/trend.rb
class Trend < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true
  validates :description, presence: true

  attr_accessible :name, :description, :active

  scope :active_trends, where(active: true)
end

app/controllers/admin/trends_controller.rb
# -*- encoding: utf-8 -*-
class Admin::TrendsController < Admin::BaseController
  before_filter :find_trend, only: [:show, :edit, :update, :destroy]

  def new
    @trend = Trend.new
  end

  def create
    @trend = Trend.new(params[:trend])
    if @trend.save
      redirect_to admin_trends_path, flash: {success: "Тренд успешно создан."}
    else
      flash.now[:error] = "Тренд не создан"
      render :new
    end
  end

  def index
    @trends = Trend.order("active DESC, created_at DESC")
  end

  def show
  end

  def edit
  end

  def update
    if @trend.update_attributes(params[:trend])
      redirect_to admin_trends_path, flash: {success: "Тренд успешно изменен."}
    else
      flash.now[:error] = "Тренд не изменен."
      render :edit
    end
  end

  def destroy
    @trend.destroy
    redirect_to admin_trends_path, flash: {success: "Тренд успешно удален."}
  end

private
  def find_trend
    @trend = Trend.find(params[:id])
  end
end

app/controllers/api/v1/trends_controller.rb
class Api::V1::TrendsController < ApplicationController
  def index
    @trends = Trend.scoped
  end
end

app/views/admin/trends/_form.html.haml
= simple_form_for [:admin, @trend], html: {class: 'form-horizontal' } do |f|

  = f.input :name, label: "Имя"
  = f.input :description, label: "Описание"
  = f.input :active, label: "Активность"
  .form-actions
    - if params[:action] == "edit"
      = f.button :submit, 'Сохранить'
    - else
      = f.button :submit, 'Создать тренд.'

app/views/admin/trends/edit.html.haml
= render 'form'

app/views/admin/trends/index.html.haml
.row
  %h3.span18.offset1= "Тренды - #{@trends.count}"
.row
  %table.table.span18.offset1
    %tr
      %th Имя
      %th Статей
      %th Активность
      %th Действия
    - @trends.each do |trend|
      %tr
        %td= link_to trend.name, admin_trend_path(trend)
        %td= link_to trend.articles.count, admin_trend_path(trend)
        %td= link_to (trend.active? ? "Да" : "Нет"), admin_trend_path(trend)
        %td
          = link_to "Изменить", edit_admin_trend_path(trend)
          = link_to "Удалить", admin_trend_path(trend), method: :delete

app/views/admin/trends/new.html.haml
= render 'form'

app/views/admin/trends/show.html.haml
.row
  .span17
    %h3= @trend.name
    %small
      Статей
      = @trend.articles.count
.row
  .span17
    = render 'articles_table', articles: @trend.articles