config/routes.rb
Kavaggregator::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :articles, only: [:index, :show]
  resources :comments, only: [:index, :create, :destroy, :new]
  resources :messages, only: [:index]
  match "feedbacks" => "feedbacks#send_feedback"

  namespace :admin do
    resources :published_articles, only: [:index] do
      collection do
        match :group
      end
      member do
        match :trend
        match :ungroup
      end
    end
    root :to => "articles#index"
    resources :news_sources do
      member do
        match :clear
      end
    end
    resources :keywords
    resources :categories
    resources :tags
    resources :trends
    resources :users
    resources :comments, only: [:index, :destroy, :show]
    resources :articles do
      member do
        match :train
        match :classify
      end
      collection do
        match :feed_me
      end
    end
    resources :messages
  end

  root to: "articles#index"

  # API
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :articles do
        member do
          post :share
          get :share
        end
      end
      resources :trends,       only: [:index]
      resources :categories,   only: [:index]
      resources :news_sources, only: [:index]
    end
  end

end

app/models/article.rb
# -*- encoding: utf-8 -*-
require "classifier"
require "date"
require "sitemap_generator"
require "checker"
require "hstore_methods"

class Article < ActiveRecord::Base
  include ActionView::Helpers::DateHelper
  include HstoreMethods
  serialize :properties, ActiveRecord::Coders::Hstore

  DEFAULT_IMAGE = '/assets/default_news.png'

  attr_accessible :text, :title, :url, :img_url, :published, :news_source_id, :category_id, :tag_ids, :summary, :article_group_id, :trend_id, :properties, :rating

  define_boolean(:reviewed, :shared, :sticky)
  define_integer(:review_count, :votes)

  belongs_to :category
  belongs_to :news_source
  belongs_to :article_group, counter_cache: true
  belongs_to :trend

  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags

  validates :title,  presence: true
  validates :text, presence: true
  validates :news_source_id, presence: true

  scope :published     ,lambda { where(published: true)}
  scope :not_published ,lambda { where(published: false)}

  after_update :fix_counter

  def fix_counter
    if group_id = self.article_group_id
      ArticleGroup.reset_counters(group_id, :articles)
    end
  end

  def self.text_search(query)
    if query.present?
      rank = <<-RANK
        ts_rank(to_tsvector('russian', title), plainto_tsquery('russian', #{sanitize(query)})) +
        ts_rank(to_tsvector('russian', text), plainto_tsquery('russian', #{sanitize(query)}))
      RANK
      # where("title @@ :q or text @@ :q", q: "#{query}").order("#{rank} DESC")
      where("title @@ :q or text @@ :q", q: "#{query}").order("created_at DESC")
    else
      scoped
    end
  end

  def self.feed_me
    NewsSource.active.each do |source|
      feed = Feedzirra::Feed.fetch_and_parse(source.url)
      next if feed.class == Fixnum or feed.nil?
      feed.entries.each do |entry|
        next if VisitedPage.find_by_url(entry.url)
        page = Page.new(entry.url)
        page.process do |html|
          PageProcessor.process(
            html,
            [ImageProcessor, IgnoredProcessor, AttributeProcessor, LinkProcessor],
            { find: source.find_helper,
              ignored: source.ignore_helper,
              host: URI.parse(URI.encode(entry.url)).host })
        end

        if check_page(page) and Article.find_by_url(entry.url).nil?
          if entry.summary and entry.summary.length > 0
            summary = Nokogiri::HTML(entry.summary).text[0..300]
          else
            summary = page.summary
          end
          article = Article.create!(title: entry.title, url: entry.url,
                          news_source_id: source.id,
                          img_url: page.image, text: page.text, summary: summary)
          article.calculate_hotness!
        end
        VisitedPage.create(url: entry.url)
      end
    end
  end

  def self.check_page(page)
    checkers = [RequiredWordsCheck, ArticleLengthCheck, ExcludedWordCheck]
    checkers.each do |checker|
      ch = checker.new(page.text)
      return false unless ch.check
    end
    true
  end

  def train(category)
    text = Nokogiri::HTML(self.text).text
    if send(:get_words, text).count < 150
      cl = FisherClassifier.new()
      cl.train(text, category)
    end
    self.update_attributes(category_id: category.id, published: true, article_group_id: ArticleGroup.create.id)
  end

  def published_date
    if created_at < DateTime.now - 3
      created_at.to_s(:ru_datetime)
    else
      time_ago_in_words(self.created_at) + " назад"
    end
  end

  def source_name
    if news_source then news_source.name else "Источник не указан" end
  end

  def category_name
    if category then category.name else "" end
  end

  def comments_count
    comments.count
  end

  def self.fetch_and_classify(days = 7, percent = 25)
    cl = FisherClassifier.new
    feed_me
    Article.not_published.order("created_at DESC").each do |art|
      text = Nokogiri::HTML(art.text).text
      next if send(:get_words, text).count > 500
      res = cl.classify(text)
      art.update_attributes(published: true, category_id: res[0].id, article_group_id: ArticleGroup.create.id) if res[0]
    end

    # grouper = ArticleGrouper.new(Article.published.where("created_at >= ?", DateTime.now - days), percent)
    # grouper.group()
    ArticleGroup.includes(:articles).where(articles: {article_group_id: nil}).destroy_all
  end

  def nested_articles
    group = self.article_group
    return [] unless group
    group.articles.order("created_at DESC").where("id != ?", self.id)
  end

  def nested_article_ids
    group = self.article_group
    return [] unless group
    group.article_ids
  end

  def self.group_similar(days = 7, percent=20)
    grouper = ArticleGrouper.new(Article.published.where("created_at >= ?", DateTime.now - days), percent)
    grouper.group()
    ArticleGroup.includes(:articles).where(articles: {article_group_id: nil}).destroy_all
  end

  def self.filter_articles(params)
    ArticleFilter.filter(params)
  end

  def other_articles
    @other_articles = []
    if self.trend
      @other_articles << Article.order("updated_at DESC").where("updated_at < ?", self.updated_at).limit(3)
      @other_articles << self.trend.articles.order("updated_at DESC").where("updated_at < ?", self.updated_at).limit(12)
    else
      @other_articles << Article.order("updated_at DESC").where("updated_at < ?", self.updated_at).limit(3)
      Trend.active_trends.order("updated_at DESC").limit(4).each {|t| @other_articles << t.articles.where("updated_at < ?", self.updated_at).order("updated_at DESC").limit(3)}
    end
    @other_articles.flatten!
  end

  def calculate_hotness!
    p = PopularityChecker.new(self.url)

    seconds = (self.created_at.to_i - Time.local(2010, 8, 10, 7, 46, 43).to_time.to_i).to_i
    s = p.likes
    displacement = Math.log( [s.abs, 1].max,  10 )

    self.rating = (displacement + ( seconds / 45000 )).to_i
    self.votes = s
    self.save
  end
end

app/controllers/admin/articles_controller.rb
# -*- encoding: utf-8 -*-
class Admin::ArticlesController < Admin::BaseController
  before_filter :update_user_state, only: [:index, :show]

  def index
    @categories = Category.order(:name)
    @articles = Article.not_published.order("created_at DESC")
  end

  def destroy
    if params[:id] == "all"
      Article.not_published.destroy_all
      redirect_to :back, flash: {:success => "Все статьи удалены."}
    else
      @article = Article.find(params[:id])
      @article.destroy
      respond_to do |format|
        format.html { redirect_to :back, flash: {:success => "Статья успешно удалена."} }
        format.js { render nothing: true, status: 200, content_type: "text/javascript"}
      end
    end
  end

  def train
    cat = Category.find_by_id(params[:cat_id])
    article = Article.find_by_id(params[:id])
    if cat && article
      article.train(cat)
      flash = {success: "Статья успешно классифицирована."}
    else
      flash = {error: "Статья не классифицирована."}
    end
    redirect_to admin_articles_path, flash: flash
  end

  def classify
    @article = Article.find(params[:id])
    @cl = FisherClassifier.new
    res = @cl.classify(Nokogiri::HTML(@article.text).text)
    @cat = res[0]
    @prob = res[1]
  end

  def feed_me
    Article.feed_me
    redirect_to admin_articles_path
  end

  def update_user_state
    current_user.touch if current_user
  end

  def new
    @article = Article.new
    @title = "Новая статья"
  end

  def edit
    @article = Article.find(params[:id])
    @title = "Редактирование статьи"
  end

  def create
    @article = Article.new(params[:article])
    @article.article_group_id = ArticleGroup.create.id
    if @article.save
      flash[:success] = "Статья успешно добавлена."
      redirect_to article_path(@article)
    else
      flash[:error] = "Статья не добавлена"
      render :new
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:success] = "Статья успешно изменена."
      respond_to do |format|
        format.html {redirect_to article_path(@article)}
        format.json { render nothing: true, content_type: 'text/javascript'}
      end
    else
      flash[:error] = "Статья не изменена"
      render :edit
    end
  end
end

app/controllers/api/v1/articles_controller.rb
require "curb"
class Api::V1::ArticlesController < ApplicationController
  def index
    @filter = Article.filter_articles(params)
    @articles = @filter[:articles]
  end

  def share
    article = Article.find(params[:id])
    article.shared = true
    article.save
    short_text = params[:short_text] || ''
    text =       params[:text] || ''
    url =        params[:url] || ''
    c = Curl::Easy.http_post(
      "http://91.205.130.20/api/v1/message_sets",
      Curl::PostField.content('api_key', ENV['multiposting_key']),
      Curl::PostField.content('message[short_text]', short_text),
      Curl::PostField.content('message[text]',       text),
      Curl::PostField.content('message[url]',        url)
    ) unless Rails.env == 'test'
    render nothing: true
  end
end

app/controllers/articles_controller.rb
# -*- encoding: utf-8 -*-
class ArticlesController < ApplicationController
  before_filter :update_user_state, only: [:index, :show]

  def index
    @filter = Article.filter_articles(params.merge(order: "created_at DESC"))
    @articles = Article.published.has_sticky(true) + @filter[:articles]
    @page_info = page_info(@filter)

    if trend = Trend.find_by_id(@filter[:trend_id])
      @meta = trend.description
    elsif tag = Tag.find_by_id(@filter[:tag_id])
      @meta = tag.description
    end

    @message = Message.order(:created_at).last

  end

  def show
    @article = Article.find(params[:id])
    @meta = (@article.summary || "Новости на ").truncate(56) + "... Кавигатор - Новости Дагестана"
    @similar_articles = @article.article_group ? @article.article_group.articles.where("id != ?", @article.id) : []
    @other_articles = @article.other_articles
    @comments = @article.comments.order("created_at ASC").page(params[:page]).per_page(15)
    @comment = @article.comments.new
  end

  def update_user_state
    current_user.touch if current_user
  end

end

app/helpers/article_helper.rb
# -*- encoding: utf-8 -*-
module ArticleHelper
  def article_category_link(article)
    if article.category
      link_to article.category.name, articles_path(cat_id: article.category)
    else
      raw("&nbsp;")
    end
  end

  def article_source_link(article)
    link_to article.news_source.name, articles_path(source_id: article.news_source.id), target: "_blank"
  end

  def large_article_sign(article)
    if send(:words_count, Nokogiri::HTML(article.text).text) > 300
      link_to raw("&nbsp"), article_path(article), class: "icon-list"
    else
      raw("&nbsp;")
    end
  end
end

app/views/admin/articles/_admin_articles_block.html.haml
- if permitted_to?(:manage, :admin_articles)
  = form_for article do |f|
    .row
      .span12
        - @categories.each do |cat|
          = link_to cat.name, train_admin_article_path(article.id, cat_id: cat.id), method: :post
      .span2= link_to "Удалить", admin_article_path(article), method: :delete, remote: true, success: "hide_field()", class: "delete_article"
      .span2= link_to "Открепить", ungroup_admin_published_article_path(article) if defined?(nested)
    .row
      - active = article.shared ? 'label info' : ''
      .span3{class: active}= link_to "Поделиться", "http://multiposting.tk/message_sets/new", target: :blank, class: "share_button"
      .span4.offset1
        = link_to "Редактировать", edit_admin_article_path(article)
      .span3
        %i.icon-file
        = article.rating
    .row
      .span6
        = f.select :trend_id, options_for_select(@admin_trends.map{|t| [t.name, t.id]}, article.trend_id), {include_blank: true}, class: "choosen_select"
      .span6
        = f.select :tag_ids, options_for_select(@tags.map{|t| [t.name, t.id]}, article.tag_ids), {}, multiple: true, class: "choosen_select"
      .span4
        Прикреплено
        = f.check_box :sticky,{}, "true", "false"
  = render 'share_popup', article: article
  :javascript
    $('.choosen_select').chosen({
      allow_single_deselect: true,
      no_results_text: 'No results matched',
      width: '200px',
      placeholder_text: '\0'
    });

app/views/admin/articles/_form.html.haml
= content_for :meta do
  = javascript_include_tag('tinymce')
= simple_form_for [:admin, @article] do |f|

  = f.input :title, label: "Заголовок"
  = f.input :summary, label: "Сводка"
  = f.input :text, label: "Текст", input_html: {class: "tinymce", cols: 150}
  :javascript
    tinyMCE.init({
      selector: '.tinymce',
      plugins: "media anchor link visualblocks code hr table textcolor image",
      width: 694,
      paste_data_images: true,
      language : 'ru',
      image_advtab: true,
      height: 500,
      toolbar1: "newdocument bold italic underline strikethrough alignleft aligncenter alignright alignjustify styleselect formatselect fontselect fontsizeselect cut copy paste bullist numlist outdent indent blockquote undo redo removeformat subscript superscript",
      toolbar2: "media link anchor visualblocks code hr textcolor image",
      tools: "inserttable"
    });
  = f.input :published, label: "Опубликовано"
  = f.input :sticky, label: "Прикреплено", as: :radio_buttons
  = f.association :news_source, include_blank: false, label: "Источник новости", input_html: {class: "choosen_select"}
  = f.association :category, include_blank: false, label: "Категория", input_html: {class: "choosen_select"}
  = f.association :trend, include_blank: true, label: "Тренд", input_html: {class: "choosen_select"}
  = f.input :img_url, label: "Ссылка на изображение", as: :string, :input_html => { :value => Article::DEFAULT_IMAGE }
  = f.input :url, label: "Ссылка на источник", as: :string
  = f.input :rating, label: "Рейтинг", as: :string
  = f.input :votes, label: "Лайки"
  = f.association :tags, label: "Тэги", input_html: {class: "choosen_select"}
  .form-actions
    - if params[:action] == "edit"
      = f.button :submit, 'Сохранить'
    - else
      = f.button :submit, 'Создать статью'

app/views/admin/articles/classify.html.haml
= @cat.name
= @prob

app/views/admin/articles/edit.html.haml
.row
  %h3.span18.offset1= "Изменение статьи."
.row
  .span17.offset1
    = render 'form'

app/views/admin/articles/find_similar.html.haml
- @articles.each do |art|
  = render 'articles/article', article: art

app/views/admin/articles/index.html.haml
.row
  .span18.offset1
    = link_to "Очистить все", admin_article_path(id: "all"), method: :delete
%ul.articles_container
  - @articles.each do |article|
    = render 'articles/article', article: article

app/views/admin/articles/new.html.haml
.row
  %h3.span18.offset1= "Новая статья"
.row
  .span17.offset1
    = render 'form'