config/routes.rb
Kavaggregator::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :articles, only: [:index, :show]
  resources :comments, only: [:index, :create, :destroy, :new]
  resources :messages, only: [:index]
  match "feedbacks" => "feedbacks#send_feedback"

  namespace :admin do
    resources :published_articles, only: [:index] do
      collection do
        match :group
      end
      member do
        match :trend
        match :ungroup
      end
    end
    root :to => "articles#index"
    resources :news_sources do
      member do
        match :clear
      end
    end
    resources :keywords
    resources :categories
    resources :tags
    resources :trends
    resources :users
    resources :comments, only: [:index, :destroy, :show]
    resources :articles do
      member do
        match :train
        match :classify
      end
      collection do
        match :feed_me
      end
    end
    resources :messages
  end

  root to: "articles#index"

  # API
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :articles do
        member do
          post :share
          get :share
        end
      end
      resources :trends,       only: [:index]
      resources :categories,   only: [:index]
      resources :news_sources, only: [:index]
    end
  end

end

app/models/news_source.rb
# -*- encoding: utf-8 -*-
class NewsSource < ActiveRecord::Base

  attr_accessible :name, :url, :find_helper, :ignore_helper, :period, :active

  before_save :process_attributes

  has_many :articles, dependent: :destroy

  validates :name, presence: true
  validates :url,  presence: true,
                   uniqueness: true,
                   format: /\A(http:\/\/|https:\/\/)www\.[a-zA-Z0-9\-\_\.]+\.[a-zA-Z]{2,4}(\/\S*)?\z/i
                   # format: /\A(http:\/\/|https:\/\/|\S)[a-zA-Z0-9\-\_\.]+\.[a-zA-Z]{2,3}(\/\S*)?\z/i
  validates :period, presence: true

  scope :active, ->{ where(:active => true) }

  def process_attributes
    self.ignore_helper = split_string(ignore_helper)
    self.find_helper   = split_string(find_helper)
  end

  def split_string(str)
    str.split(",").collect {|s| s.chomp.strip}.select{|s| s != ''}.join(', ') if str
  end

  def clear
    self.articles.destroy_all
    host = URI(url).host.match(/^www.(\S*)/i)[1]

    VisitedPage.where("visited_pages.url LIKE :host", host: "%#{host}%").destroy_all
  end

end

app/controllers/admin/news_sources_controller.rb
# -*- encoding: utf-8 -*-
class Admin::NewsSourcesController < Admin::BaseController

  before_filter :find_source, only: [:show, :clear, :destroy, :edit, :update]

  def index
    @news_sources = NewsSource.all
  end

  def new
    @news_source = NewsSource.new
  end

  def create
    @news_source = NewsSource.new(params[:news_source])
    if @news_source.save
      redirect_to admin_news_sources_path, flash: {success: "Источник новостей успешно создан."}
    else
      flash.now[:error] = "Источник новостей не добавлен."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @news_source.update_attributes(params[:news_source])
      redirect_to admin_news_sources_path, flash: {success: "Источник новостей успешно изменен."}
    else
      flash.now[:error] = "Источник новостей не изменен."
      render :edit
    end
  end

  def clear
    @news_source.clear
    redirect_to admin_news_sources_path, flash: {success: "Статьи успешно удалены."}
  end

  def destroy
    @news_source.destroy
    redirect_to admin_news_sources_path, flash: {success: "Источник новостей успешно удален."}
  end

private
  def find_source
    @news_source = NewsSource.find(params[:id])
  end
end

app/controllers/api/v1/news_sources_controller.rb
class Api::V1::NewsSourcesController < ApplicationController
  def index
    @news_sources = NewsSource.active
  end
end

app/views/admin/news_sources/_form.html.haml
.row
  .span18.offset1
    = simple_form_for [:admin, @news_source], html: {class: 'form-horizontal' } do |f|

      = f.input :name,          label: "Имя"
      = f.input :url,           label: "Ссылка"
      = f.input :find_helper,   label: "Поиск в пределах", as: :string
      = f.input :ignore_helper, label: "Игнорировать", as: :string
      = f.input :active,        label: "Активность"
      = f.input :period,        label: "Периодичность проверки"

      .form-actions
        - if params[:action] == 'edit'
          = f.button :submit, "Сохранить изменения"
        - else
          = f.button :submit, "Создать источник новостей"

app/views/admin/news_sources/edit.html.haml
= render 'form'

app/views/admin/news_sources/index.html.haml
.row
  %h3.span18.offset1= "Источники новостей (#{@news_sources.length})"
.row
  %table.table.span18.offset1
    %tr
      %th Название
      %th Статей
      %th URL
      %th Действия
    - @news_sources.each do |source|
      %tr
        %td= link_to source.name, admin_news_source_path(source)
        %td= link_to source.articles.count, admin_news_source_path(source)
        %td= link_to source.url, source.url, target: "_blank"
        %td= link_to "Удалить", admin_news_source_path(source), method: :delete
        %td= link_to "Изменить", edit_admin_news_source_path(source)
        %td= link_to "Очистить", clear_admin_news_source_path(source), method: :post

app/views/admin/news_sources/new.html.haml
= render 'form'

app/views/admin/news_sources/show.html.haml
.row
  .span18.offset1
    %h3= @news_source.name
    %h4= link_to @news_source.url, @news_source.url, target: "_blank"
.row
  .span18.offset1
    %h4= "Статей: #{@news_source.articles.count.to_s}"
    = render 'articles_table', articles: @news_source.articles.order(:created_at)