config/routes.rb
Kavaggregator::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :articles, only: [:index, :show]
  resources :comments, only: [:index, :create, :destroy, :new]
  resources :messages, only: [:index]
  match "feedbacks" => "feedbacks#send_feedback"

  namespace :admin do
    resources :published_articles, only: [:index] do
      collection do
        match :group
      end
      member do
        match :trend
        match :ungroup
      end
    end
    root :to => "articles#index"
    resources :news_sources do
      member do
        match :clear
      end
    end
    resources :keywords
    resources :categories
    resources :tags
    resources :trends
    resources :users
    resources :comments, only: [:index, :destroy, :show]
    resources :articles do
      member do
        match :train
        match :classify
      end
      collection do
        match :feed_me
      end
    end
    resources :messages
  end

  root to: "articles#index"

  # API
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :articles do
        member do
          post :share
          get :share
        end
      end
      resources :trends,       only: [:index]
      resources :categories,   only: [:index]
      resources :news_sources, only: [:index]
    end
  end

end

app/models/user.rb
# -*- encoding: utf-8 -*-
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :provider, :uid, :salt

  validates_presence_of :name
  has_many :comments

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      if ["twitter"].include?(auth.provider) and auth.info.email.nil?
        user.email = "#{auth.info.nickname}@#{auth.provider}.com"
      end
    end
  end

  def online?
    self.updated_at >= 5.minutes.ago
  end

  def offline
    self.updated_at = 6.minutes.ago
    self.save
  end

  def role_symbols
    user_role = self.role
    if user_role then [user_role.to_sym] else [:guest] end
  end

  def user_role
    roles = {"administrator" => "Администратор", "user" => "Пользователь", "moderator" => "Модератор"}
    roles[self.role]
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes'], without_protection: true) do |user|
        user.attributes = params
        user.valid?
        session['devise.user_attributes'] = nil
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

end

app/controllers/admin/users_controller.rb
# -*- encoding: utf-8 -*-
class Admin::UsersController < Admin::BaseController

  before_filter :find_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, flash: {success: "Пользователь успешно удален."}
  end

  def edit
  end

  def update
    @user.role = params[:user][:role]
    @user.save
    redirect_to admin_users_path, flash: { success: "Роль пользователя успешно изменена." }
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/admin/users/edit.html.haml
= simple_form_for [:admin, @user], html: {class: "form-horizontal"} do |f|
  = f.input :role, as: :select, include_blank: false, collection: [["Администратор", "administrator"], ["Модератор", "moderator"], ["Пользователь", "user"]], label: "Роль"
  .form-actions
    = f.submit "Изменить"

app/views/admin/users/index.html.haml
.row
  .span17
    %h3.span6
      Пользователей:
      = @users.count
      %small
        Онлайн:
        = @users.inject(0){|sum, u| sum += u.online? ? 1 : 0 }
  .row
    .span17
      %table.table
        %tr
          %th Имя
          %th Роль
          %th Провайдер
          %th Онлайн?
          %th Действия
        - @users.each do |user|
          %tr(id="user_#{user.id}")
            %td= user.name
            %td= user.user_role
            %td= user.provider || "kavigator"
            %td= user.online? ? "online" : "offline"
            %td
              = link_to "Удалить", admin_user_path(user), method: :delete
              = link_to "Изменить", edit_admin_user_path(user)